MVC_News/MVC_News/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_News.Models;

namespace MVC_News.Controllers
{
    [Authorize(Roles ="admin")]
    public class CategoryController : Controller
    {
        private readonly NewsDbContext dbContext;
        public CategoryController(NewsDbContext db)
        {
            dbContext = db;
        }
        public async Task<IActionResult> Index()
        {
            return View(await dbContext.Categories.ToListAsync());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            if (ModelState.IsValid)
            {
                dbContext.Add(category);
                await dbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(category);
        }
        public async Task<IActionResult> Edit(int id)
        {
            if (id==null || dbContext.Categories==null)
            {
                return NotFound();
            }
            var category = await dbContext.Categories.FindAsync(id);
            if (category==null)
            {
                return NotFound();
            }
            return View(category);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Category category)
        {
            if (id!=category.Id)
            {
                return NotFound();
            }
            if(ModelState.IsValid)
            {
                try
                {
                    dbContext.Update(category);
                    await dbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(category);
        }
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null || dbContext.Categories == null)
            {
                return NotFound();
            }
            var category = await dbContext.Categories.FirstOrDefaultAsync(c => c.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
        [HttpPost,ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (dbContext.Categories == null) 
            { 
                return Problem("Entity set 'NewsDbContext.Categories'  is null."); 
            }
            var category = await dbContext.Categories.FindAsync(id);
            if (category != null)
            {
                dbContext.Categories.Remove(category);
            }
            await dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        private bool CategoryExists(int id)
        {
            return dbContext.Categories.Any(c => c.Id == id);
        }
    }
}

MVC_News/MVC_News/Controllers/NewsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_News.Models;

namespace MVC_News.Controllers
{
    public class NewsController : Controller
    {
        private readonly NewsDbContext db ;
        public NewsController(NewsDbContext dbContext)
        {
            db = dbContext;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            ViewBag.Categories = new SelectList(db.Categories.ToList(), "Id", "Name");
            var newsItems = db.NewsItems.Include(n => n.Category).ToList();
            return View(newsItems);
        }
        [HttpPost]
        public IActionResult Index(int? CategoryId)
        {
            ViewBag.Categories = new SelectList(db.Categories.ToList(), "Id", "Name");
            if (CategoryId == null)
                return View(db.NewsItems.Include(n => n.Category).ToList());
            else
            {
                var category = db.Categories.Include(i => i.NewsItems).FirstOrDefault(c => c.Id == CategoryId);
                return View(category.NewsItems.ToList());
            }
        }

        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            var model = db.NewsItems.FirstOrDefault(n => n.Id == id);
            return View(model);
        }
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(db.Categories.ToList(), "Id", "Name");
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create(NewsItem newsItem,IFormFile ImgSrc)
        {
            if (ModelState.IsValid)
            {
                newsItem.CreatedDate = DateTime.Now;
                db.Add(newsItem);
                await db.SaveChangesAsync();
                if (ImgSrc != null)
                {
                    string imgName = newsItem.Id.ToString() + "." + ImgSrc.FileName.Split(".").Last();
                    using (var obj = new FileStream(@".\wwwroot\images\" + imgName, FileMode.Create))
                    {
                        await ImgSrc.CopyToAsync(obj);
                        newsItem.ImgSrc = imgName;
                        await db.SaveChangesAsync();
                    }
                }
                return RedirectToAction("Index");
            }
            ViewBag.Categories = new SelectList(db.Categories.ToList(), "Id", "Name", newsItem.CategoryId);
            return View(newsItem);
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || db.NewsItems == null)
            {
                return NotFound();
            }
            var newsItem = await db.NewsItems.FindAsync(id);
            if (newsItem == null)
            {
                return NotFound();
            }
            ViewBag.Categories = new SelectList(db.Categories.ToList(), "Id", "Name");
            return View(newsItem);
        }
        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id, NewsItem newsItem,IFormFile ImgSrc)
        {
            if (id != newsItem.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    newsItem.CreatedDate = DateTime.Now;
                    db.Update(newsItem);
                    await db.SaveChangesAsync();
                    if (ImgSrc != null)
                    {
                        string imgName = newsItem.Id.ToString() + "." + ImgSrc.FileName.Split(".").Last();
                        using (var obj = new FileStream(@".\wwwroot\images\" + imgName, FileMode.Create))
                        {
                            await ImgSrc.CopyToAsync(obj);
                            newsItem.ImgSrc = imgName;
                            await db.SaveChangesAsync();
                        }
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewsItemExists(newsItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction("Index");
            }
            ViewBag.Categories = new SelectList(db.Categories.ToList(), "Id", "Name", newsItem.CategoryId);
            return View(newsItem);
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null || db.NewsItems == null)
            {
                return NotFound();
            }
            var newsItem = await db.NewsItems.FirstOrDefaultAsync(n => n.Id == id);
            if (newsItem == null)
            {
                return NotFound();
            }
            return View(newsItem);
        }
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (db.NewsItems == null)
            {
                return Problem("Entity set 'NewsDbContext.NewsItems'  is null.");
            }
            var newsItem = await db.NewsItems.FindAsync(id);
            if (newsItem != null)
            {
                db.NewsItems.Remove(newsItem);
            }
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        private bool NewsItemExists(int id)
        {
            return db.NewsItems.Any(n => n.Id == id);
        }

    }
}

MVC_News/MVC_News/Views/Shared/LoginPartial.cshtml
@if (!User.Identity.IsAuthenticated)
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
    </li>
}

MVC_News/MVC_News/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - News</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_News.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="News" asp-action="Index"><img width="40" height="40" src="~/images/logo.png" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="News" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("admin")) {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                            </li>
                        }
                        <partial name="LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVC_News - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>



@*    I will Prepair nav Style Later*@
@*<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-controller="News" asp-action="Index"><h1>News</h1></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="News" asp-action="Index"><i class="bi bi-film"></i> Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="bi bi-gear"></i> Categories
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-controller="News" asp-action="Index"><i class="bi bi-camera-reels"></i> Cinemas</a>
                            <a class="dropdown-item" asp-controller="News" asp-action="Index"><i class="bi bi-headset"></i> Producers</a>
                            <a class="dropdown-item" asp-controller="News" asp-action="Index"><i class="bi bi-person-square"></i> Actors</a>
                        </div>
                    </li>
                    <select id="SubjectList" name="SubjectList">
                        <option value="1">Physics</option>
                        <option value="2">Chemistry</option>
                        <option value="3">Mathematics</option>
                    </select>

                </ul>
            </div>
        </div>
    </nav>
</header>
@RenderBody()
<footer></footer>*@